// Build the inline icon registry (src/ui/components/icons.ts) from Lucide.
//
// Rationale (Phase 18): the app follows a "bundle vector assets, no CDN, no runtime icon
// dependency" rule (same as the flags). So instead of importing an icon library at runtime,
// we copy *only the icons we actually use* — as inline SVG inner markup — into a small
// generated registry. `lucide-static` is a devDependency used solely as the source here; it
// is never shipped. Icons are from Lucide (https://lucide.dev), ISC License.
//
// To add an icon: add `ourName: 'lucide-file-name'` to ICONS below and rerun:
//   node scripts/build-icons.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const ICON_DIR = join(here, '..', 'node_modules', 'lucide-static', 'icons');
const OUT = join(here, '..', 'src', 'ui', 'components', 'icons.ts');

// our semantic name  ->  lucide icon file (without .svg)
const ICONS = {
  // nav + primary actions
  home: 'house',
  play: 'play',
  history: 'chart-column',
  settings: 'settings',
  custom: 'sliders-horizontal',
  train: 'dumbbell',
  // session types
  fixed: 'list-checks',
  survival: 'heart',
  // achievements
  target: 'target',
  award: 'award',
  shield: 'shield-check',
  bolt: 'zap',
  flame: 'flame',
  calendar: 'calendar-days',
  'calendar-check': 'calendar-check',
  map: 'map',
  gem: 'gem',
  crown: 'crown',
  medal: 'medal',
  globe: 'globe',
  // explorer rank medals — the per-rank "journey" glyphs embossed on each rank's medal
  // (Novice → Legend). map/globe/crown above are reused for the top three rungs.
  flag: 'flag', // Novice — first flag planted
  compass: 'compass', // Scout
  signpost: 'signpost-big', // Wanderer
  route: 'route', // Pathfinder
  navigation: 'navigation', // Navigator
  sailboat: 'sailboat', // Voyager
  mountain: 'mountain-snow', // Adventurer
  landmark: 'landmark', // capital-mastery meter + capital achievements (Phase 24)
  languages: 'languages', // language-mastery meter + language achievements (Phase 23)
  factory: 'factory', // industry-mastery meter + industry achievements (Phase 25)
  // misc UI
  party: 'party-popper',
  check: 'check',
  clock: 'clock',
  trophy: 'trophy',
  repeat: 'repeat',
  sparkles: 'sparkles',
  'chevron-right': 'chevron-right',
  reset: 'rotate-ccw',
  search: 'search', // targeted-practice country picker (Phase 27)
  plus: 'plus', // "New set" in targeted practice (Phase 27); map zoom-in (Phase 37)
  minus: 'minus', // map zoom-out (Phase 37)
  maximize: 'maximize', // map "fit / reset view" control (Phase 37)
  trash: 'trash-2', // delete a saved custom set (Phase 27)
  // PWA "add to home screen" install hint (mobile) — OS glyphs shown in the step list so a
  // user can recognise the real button to tap, plus the sheet's header/close controls.
  close: 'x', // dismiss the install prompt
  smartphone: 'smartphone', // install-prompt header illustration
  share: 'share', // iOS Safari share-sheet button (box with up arrow)
  'add-home': 'square-plus', // the "Add to Home Screen" row glyph
  'menu-dots': 'ellipsis-vertical', // Android browser overflow (⋮) menu
  install: 'download', // one-tap / generic "Install" action
};

/** Pull the inner markup out of a Lucide <svg> wrapper and compact whitespace. */
function innerMarkup(file) {
  const svg = readFileSync(join(ICON_DIR, `${file}.svg`), 'utf8');
  const m = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!m) throw new Error(`Could not parse ${file}.svg`);
  return m[1].replace(/\s+/g, ' ').trim();
}

const entries = Object.entries(ICONS)
  .map(([name, file]) => `  '${name}': \`${innerMarkup(file)}\`,`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
//
// Inline SVG icon registry. Icons are from Lucide (https://lucide.dev), ISC License; only the
// icons the app uses are copied here, so there is no runtime icon dependency and the bundle
// stays minimal. Each value is the inner markup of a 24x24 stroke glyph, rendered by Icon.svelte
// (which supplies the <svg> wrapper, currentColor stroke, and sizing).
//
// To add an icon: edit scripts/build-icons.mjs and rerun \`node scripts/build-icons.mjs\`.

export const icons = {
${entries}
} as const;

export type IconName = keyof typeof icons;
`;

writeFileSync(OUT, out);
console.log(`Wrote ${Object.keys(ICONS).length} icons to ${OUT}`);
