// Runtime loaders/accessors over the bundled country dataset (Phase 1).
//
// The dataset is generated by `scripts/build-data.mjs` and imported as plain JSON,
// so there is no runtime processing beyond building a few lookup indexes once.

import type { Country, RegionNode, RegionTree, SubregionNode } from './types';
import generated from './generated/countries.json';

// The generated JSON is the single source of truth; assert its shape once here.
const countries: readonly Country[] = generated as Country[];

const byIso2 = new Map<string, Country>(countries.map((c) => [c.iso2, c]));
const byIso3 = new Map<string, Country>(countries.map((c) => [c.iso3, c]));

// Flag SVGs are resolved through Vite so the emitted URLs respect the app's base
// path and get content-hashed for caching. Keys look like "./generated/flags/bg.svg".
const flagUrls = import.meta.glob<string>('./generated/flags/*.svg', {
  eager: true,
  query: '?url',
  import: 'default',
});

/** All in-scope countries, sorted by English name. Returns a fresh array. */
export function getCountries(): Country[] {
  return countries.slice();
}

/** The number of countries in the dataset. */
export function countryCount(): number {
  return countries.length;
}

/** Look up a country by ISO alpha-2 or alpha-3 code (case-insensitive). */
export function getCountry(iso: string): Country | undefined {
  const key = iso.toUpperCase();
  return byIso2.get(key) ?? byIso3.get(key);
}

/** Resolve a bundled flag SVG to a URL usable in `<img src>` / CSS. */
export function flagUrl(country: Country | string): string {
  const c = typeof country === 'string' ? getCountry(country) : country;
  if (!c) throw new Error(`flagUrl: unknown country "${String(country)}"`);
  const url = flagUrls[`./generated/${c.flagAsset}`];
  if (!url) throw new Error(`flagUrl: no bundled flag for "${c.iso2}" (${c.flagAsset})`);
  return url;
}

/** The distinct regions, in first-appearance (alphabetical) order. */
export function getRegions(): string[] {
  return [...new Set(countries.map((c) => c.region))];
}

/** The distinct sub-regions within a region. */
export function getSubregions(region: string): string[] {
  return [...new Set(countries.filter((c) => c.region === region).map((c) => c.subregion))];
}

/** All countries in a region. */
export function getCountriesByRegion(region: string): Country[] {
  return countries.filter((c) => c.region === region);
}

/** All countries in a sub-region. */
export function getCountriesBySubregion(subregion: string): Country[] {
  return countries.filter((c) => c.subregion === subregion);
}

/**
 * Build the full `region → sub-region → countries` index. Regions, sub-regions,
 * and countries are each sorted alphabetically (countries by English name).
 */
export function getRegionTree(): RegionTree {
  const byName = (a: Country, b: Country) => a.name.en.localeCompare(b.name.en, 'en');

  const regionMap = new Map<string, Map<string, Country[]>>();
  for (const c of countries) {
    let subMap = regionMap.get(c.region);
    if (!subMap) regionMap.set(c.region, (subMap = new Map()));
    let list = subMap.get(c.subregion);
    if (!list) subMap.set(c.subregion, (list = []));
    list.push(c);
  }

  const tree: RegionNode[] = [];
  for (const region of [...regionMap.keys()].sort((a, b) => a.localeCompare(b, 'en'))) {
    const subMap = regionMap.get(region)!;
    const subregions: SubregionNode[] = [];
    const regionCountries: Country[] = [];
    for (const subregion of [...subMap.keys()].sort((a, b) => a.localeCompare(b, 'en'))) {
      const list = subMap.get(subregion)!.slice().sort(byName);
      subregions.push({ subregion, countries: list });
      regionCountries.push(...list);
    }
    regionCountries.sort(byName);
    tree.push({ region, subregions, countries: regionCountries });
  }
  return tree;
}
