// Data layer: static bundled dataset + persistence.
//
// The normalized country/region dataset and its typed accessors live here, alongside
// the IndexedDB persistence wrapper (history, SR state, prefs) added in Phase 6 — see
// `persistence/`, which exposes a storage-agnostic `QuizStore` port with IndexedDB
// and in-memory implementations.
//
// The dataset itself is generated by `scripts/build-data.mjs` into `generated/`.

export type {
  Country,
  CountryName,
  LanguageRef,
  RegionNode,
  RegionTree,
  SubregionNode,
} from './types';

export {
  getCountries,
  countryCount,
  getCountry,
  flagUrl,
  getRegions,
  getSubregions,
  getCountriesByRegion,
  getCountriesBySubregion,
  getRegionTree,
} from './countries';

export {
  type CountryFeature,
  loadTopology,
  loadCountryFeatures,
  indexFeaturesByCountry,
} from './geometry';

export type {
  AchievementUnlock,
  CustomSet,
  DailyResult,
  GrandmasterRecord,
  MapProjection,
  Prefs,
  ProgressionState,
  QuizStore,
  SessionRecord,
  SRItem,
} from './persistence';
export {
  DEFAULT_PREFS,
  MAP_PROJECTIONS,
  PREFS_BOUNDS,
  clampPrefs,
  isMapProjection,
  openStore,
  IdbQuizStore,
  MemoryQuizStore,
} from './persistence';
